version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
      - "8501:8501"
      - "8502:8502"
      - "5001:5001"
    volumes:
      - .:/app
      - ./templates:/app/templates  # テンプレートディレクトリのマウント
    environment:
      - FLASK_PORT=5000
      - STREAMLIT_PORT=8501
      - CTF_PORT=5001
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: bash -c "python main.py & python ctf.py"
